// Internal: text HUD (resources, selection info).

export function updateHUD(state, client, config, entities, selectedLive) {
  // HUD always reflects the LOCAL player's side — 'red' in SP, but either side
  // in MP (the server assigns client.playerId on connect).
  const me = state.players[client.playerId];
  // One readout per treasury resource — ids generated by client/hud-dom.js.
  for (const [id, def] of Object.entries(config.resourceTypes)) {
    if (!def.treasury) continue;
    const el = document.getElementById(`res-${id}`);
    if (el) el.textContent = Math.floor(me[id] || 0);
  }
  document.getElementById('pop').textContent  = entities.unitsOf(client.playerId).length;
  const arrowsTotal = document.getElementById('arrows-total');
  if (arrowsTotal) arrowsTotal.textContent = totalArrowsFor(state, client.playerId);

  const info = document.getElementById('selection-info');
  if (selectedLive.length === 0) {
    info.textContent = '(no selection)';
  } else if (selectedLive.length === 1) {
    info.textContent = describeEntity(selectedLive[0], config, entities);
  } else {
    info.textContent = describeSelection(selectedLive);
  }
}

const MAX_LINES = 12;

function totalArrowsFor(state, owner) {
  let n = 0;
  for (const e of state.entities) {
    if (e.hp <= 0 || e.owner !== owner) continue;
    if (e.type === 'unit' && e.kind === 'archer') n += e.arrows;
    else if (e.type === 'building' && (e.kind === 'arrowBuilding' || e.kind === 'tower')) n += e.arrows;
  }
  return n;
}

function describeSelection(selected) {
  const rows = selected.slice().sort((a, b) => (a.hp / a.maxHp) - (b.hp / b.maxHp));
  const counts = {};
  for (const s of selected) counts[s.kind] = (counts[s.kind] || 0) + 1;
  const header = 'Selected: ' + Object.entries(counts).map(([k, n]) => `${n} ${k}`).join(', ');
  const shown = rows.slice(0, MAX_LINES).map(unitLine);
  if (rows.length > MAX_LINES) shown.push(`…and ${rows.length - MAX_LINES} more`);
  return header + '\n' + shown.join('\n');
}

function unitLine(u) {
  const hp = `${Math.ceil(u.hp)}/${u.maxHp}`;
  if (u.kind === 'archer') return `${u.kind} ${hp} (${u.arrows}a)`;
  return `${u.kind} ${hp}`;
}

function describeEntity(e, config, entities) {
  if (e.type === 'unit') {
    let s = `${e.kind} (${e.owner})\nHP ${Math.ceil(e.hp)}/${e.maxHp}`;
    if (e.kind === 'archer') s += `\nArrows: ${e.arrows}/${config.unit.archer.quiver.max}`;
    if (e.job)               s += `\nJob: ${e.job}`;
    if (e.carrying)          s += `\nCarrying: ${e.carrying.amount} ${e.carrying.kind}`;
    return s;
  }
  let s = `${e.kind} (${e.owner})\nHP ${Math.ceil(e.hp)}/${e.maxHp}`;
  if (e.kind === 'arrowBuilding') {
    s += `\nWood: ${e.wood}/${config.building.arrowBuilding.woodCap}` +
         `\nArrows: ${e.arrows}/${config.building.arrowBuilding.arrowCap}`;
  }
  if (e.kind === 'tower') {
    const max = config.building.tower.garrisonMax;
    s += `\nGarrison: ${e.garrisonIds.length}/${max}`;
    s += `\nArrows: ${e.arrows}/${config.building.tower.arrowCap}`;
    for (const aId of e.garrisonIds) {
      const a = entities.byId(aId);
      if (a) s += `\n  archer ${Math.ceil(a.hp)}/${a.maxHp} (${a.arrows}a)`;
    }
  }
  if (e.kind === 'goldMine')          s += `\nGold left: ${e.gold}`;
  if (e.trainQueue && e.trainQueue.length) {
    s += `\nQueue: ${e.trainQueue.join(', ')}`;
  }
  if (e.researchQueue && e.researchQueue.length) {
    s += `\nResearching: ${e.researchQueue.map(j => j.id).join(', ')}`;
  }
  return s;
}
